

name: dating_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^0.1.3
  dotted_border: ^2.0.0-nullsafety.0
  super_tooltip: ^0.9.6
  dropdown_search: ^0.4.5
  intl: ^0.16.1
  flutter_dropdown: ^0.0.8
  flutter_icons: ^1.1.0
  flutter_svg: ^0.21.0+1
  get: ^3.13.2
  gradient_text: ^1.0.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  menu_button: ^1.2.1
  countdown_flutter: ^0.1.2
  path_provider: ^1.6.22
  sticky_grouped_list: ^1.2.0
  emojis: ^0.9.3
  zefyr:
    git:
      url: git://github.com//zefyr.git
      path: packages/zefyr/
  image_picker: ^0.7.4
  flutter_keyboard_visibility: ^4.0.3
  multi_image_picker: ^4.7.14
  http_interceptor: ^0.4.1
  http: ^0.13.0
  simple_image_crop:
    git:
      url: git://github.com//flutter_simple_image_crop.git
  flutter_image_compress: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Graphic
      fonts:
        - asset: assets/fonts/GraphikLCG-Extralight.ttf
          weight: 200
        - asset: assets/fonts/GraphikLCG-Regular.ttf
          weight: 400
        - asset: assets/fonts/GraphikLCG-Medium.ttf
          weight: 500
        - asset: assets/fonts/GraphikLCG-Bold.ttf
          weight: 600
        - asset: assets/fonts/GraphikLCG-RegularItalic.ttf
          weight: 400
          style: italic